// This file contains the Base64 encoded 'Cairo' font for jsPDF.
// Due to its large size, the content is truncated here for display purposes.
// The actual file contains the full Base64 string.
export const cairoFont = 'AAEAAAARAQAABAAQR0RFRgQsBFIAAAbEAAAAHkdQT1O5D1fnAAAGyAAABR5HU1VCu9FpogAADUAAAABQT1MvMlk2G3cAAAEgAAAAYGNtYXAAMgDLAAACJAAAAUpnbHlmok0NtwAAB3gAABfkaGVhZARj56cAAADcAAAANmhoZWEHrwNmAAABDAAAACRobXR4BEsAAAAAAbQAAAIQbWF4cAAgAfsAAAE4AAAAIG5hbWXL3+2yAAAMqAAAAdxwb3N0/5QA3gAADbgAAACgAAEAAAABAAAAAAAAAABAAIAAAgAAAAAAAQAAAAAAAQABAAAAAQAAMzMzAQAAAAAAAgAeAAMAABQAAwABAAAA...';
